### ISSUE TITLE
Trying to Compile/Build NFC-Stuff for Blackberry10

### ISSUE THREAD

**Issue by LaermTot** [chariotsolutions/phonegap-nfc#203] opened 2015-08-31 11:42 UTC
Hell I tried to 
> git clone https://github.com/chariotsolutions/phonegap-nfc.git
> cd phonegap-nfc
> ant build-javascript

>> Buildfile: build.xml not found
What am I missing here ?

Volker

**Comment by don** [comment] 2015-09-11 16:27
Duplicate of #202

**Closed by don** 2015-09-11 16:27 UTC

**Comment by don** [comment] 2015-10-26 16:34
`ant build-javascript` was for BlackBerry 7
