### ISSUE TITLE
error build with ionic v3

### ISSUE THREAD

**Issue by arsewizz** [chariotsolutions/phonegap-nfc#345] opened 2018-09-07 10:44 UTC
![nfc](https://user-images.githubusercontent.com/15099501/45214777-ae5ff780-b29b-11e8-8553-0f3bec89d648.PNG)

**Comment by don** [comment] 2018-10-09 16:55
Duplicate of #332 
Update the sourceCompatibility to JavaVersion.VERSION_1_8 in build.gradle
https://developer.android.com/studio/write/java8-support

**Closed by don** 2018-10-09 16:55 UTC
